name: Android CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # ئەم بەشە بە گیتھەب دەڵێت هەموو کارەکان لەناو ئەم فۆڵدەرەدا بکە
    defaults:
      run:
        working-directory: "UltimateEngine External"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Make gradlew executable or create it
      run: |
        if [ -f "gradlew" ]; then
          echo "gradlew found! Granting permission..."
          chmod +x gradlew
        else
          echo "gradlew not found! Generating gradle wrapper..."
          gradle wrapper
          chmod +x gradlew
        fi

    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: My-Android-App-APK
        # لێرەدا پێی دەڵێین لەناو فۆڵدەرەکە بەدوای فایلە ئامادەکراوەکەدا بگەڕێ
        path: "UltimateEngine External/app/build/outputs/apk/debug/*.apk"
